name: vqgan
channels:
  - bioconda
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bedtools=2.30.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mysql-connector-c=6.1.6
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=25.1
  - python=3.10.4
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.38.2
  - tk=8.6.11
  - ucsc-bigwigtobedgraph=357
  - wheel=0.45.1
  - xz=5.2.10
  - zlib=1.2.11
  - pip:
      - absl-py==2.3.1
      - accelerate==1.7.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - argcomplete==3.6.2
      - argh==0.31.3
      - arrow==1.3.0
      - asciitree==0.3.3
      - astropy==6.1.7
      - astropy-iers-data==0.2025.6.23.0.39.50
      - attrs==21.4.0
      - beartype==0.21.0
      - binaryornot==0.4.4
      - bioframe==0.8.0
      - certifi==2025.4.26
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cookiecutter==2.6.0
      - cooler==0.10.3
      - cooltools==0.7.1
      - cycler==0.12.1
      - cython==3.1.2
      - cytoolz==1.0.1
      - deprecation==2.1.0
      - dill==0.4.0
      - discrete-key-value-bottleneck-pytorch==0.1.1
      - einops==0.8.1
      - einx==0.3.0
      - ema-pytorch==0.7.7
      - enformer-pytorch==0.8.10
      - filelock==3.18.0
      - fonttools==4.58.1
      - frozendict==2.4.6
      - fsspec==2025.5.1
      - future==1.0.0
      - gffutils==0.13
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.3
      - grpcio==1.73.1
      - h5py==3.13.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.3
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kipoi==0.8.6
      - kipoi-conda==0.3.1
      - kipoi-utils==0.7.7
      - kipoiseq==0.7.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - memory-efficient-attention-pytorch==0.1.6
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - natsort==8.4.0
      - ncls==0.0.68
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - optuna==4.4.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.8
      - polars==1.30.0
      - protobuf==6.31.1
      - psutil==7.0.0
      - pybedtools==0.12.0
      - pybigwig==0.3.24
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyerfa==2.0.1.5
      - pyfaidx==0.8.1.4
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyranges==0.1.4
      - pysam==0.23.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - related==0.7.3
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.0
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sorted-nearest==0.0.39
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinydb==4.8.2
      - tokenizers==0.21.1
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.7.0
      - torchmetrics==1.7.2
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.53.2
      - triton==3.3.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - vector-quantize-pytorch==1.22.16
      - wandb==0.21.0
      - werkzeug==3.1.3
